language: ruby

services:
  - docker

addons:
  apt:
    packages:
    - curl
    - git
    - shellcheck
    - python-pip

rvm:
  - ruby

env:
  matrix:
    - SUITE=rubocop
    - SUITE=shellcheck
    - SUITE=centos
    - SUITE=ubuntu
    - SUITE=debian
    - SUITE=changelog

sudo: true
dist: trusty
bundler_args: --with=docker --without vagrant windows

before_install:
  - pip install --user -r test-requirements.txt

script:
  # Enter the main test loop
  - ./ci/scripts/test-main.sh

after_script:
  # Enter the cleanup loop
  - ./ci/scripts/cleanup.rb
