language: ruby

services:
  - docker

addons:
  apt:
    packages:
    - curl
    - git
    - shellcheck
    - python-pip

rvm:
  - ruby

env:
  matrix:
    - SUITE="changelog"
    - SUITE="integration:centos"
    - SUITE="integration:debian"
    - SUITE="integration:ubuntu"
    - SUITE="rubocop"
    - SUITE="shellcheck"

sudo: true
dist: trusty
bundler_args: --with=docker --without vagrant windows

before_install:
  - pip install --user -r test-requirements.txt

script:
  # Enter the main test loop
  - bundle exec rake travis:main

after_script:
  # Enter the cleanup loop
  - bundle exec rake travis:cleanup
